### PR TITLE
add rsync package

### PR DESCRIPTION
**Pull request by glavk**
**Description of the change**

Install rsync package.

**Benefits**

Speed up backup process.

**Possible drawbacks**

No.

### CODE REVIEW

**Review by carrodher — COMMENTED** [review]
Thanks for your contribution, I agree about adding this package to the Dockerfile.
About the approach, this line is automatically generated by some internal tool so we need to maintain the one-line format and also the order, can you please add `rsync` in the same line and also alphabetically ordered?

**Comment by glavk** [comment]
Hello!
I add rsync in the same line and alphabetically ordered.

**Comment by carrodher** [comment]
Thanks for the changes. Although publicly in GitHub we are only providing the percona-xtrabackup based on Debian, internally we are also building this image based on other distros such as CentOS, PhotonOS or Ubuntu. Before merging this PR I would like to test that everything is working fine in the different distros. Once tested I will merge the PR. Thanks again!

**Comment by carrodher** [comment]
I just checked it works in all the supported distros:

- Debian
```console
$ docker build -t "carrodher/percona" .
Sending build context to Docker daemon  29.18kB
Step 1/14 : FROM docker.io/bitnami/minideb:buster
...
Step 5/14 : RUN install_packages ca-certificates curl gzip libaio1 libc6 libcom-err2 libcurl4 libev4 libffi6 libgcc1 libgcrypt20 libgmp10 libgnutls30 libgpg-error0 libgssapi-krb5-2 libhogweed4 libidn2-0 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 libnettle6 libnghttp2-14 libp11-kit0 libpsl5 librtmp1 libsasl2-2 libssh2-1 libssl1.1 libstdc++6 libtasn1-6 libunistring2 procps rsync sudo tar zlib1g
 ---> Running in a610a0333e97
Reading package lists...
Building dependency tree...
...
The following NEW packages will be installed:
  ca-certificates curl libaio1 libcom-err2 libcurl4 libev4 libgssapi-krb5-2
  libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2
  libldap-common libncurses6 libnghttp2-14 libpopt0 libprocps7 libpsl5
  librtmp1 libsasl2-2 libsasl2-modules-db libssh2-1 libssl1.1 openssl procps
  rsync sudo
0 upgraded, 27 newly installed, 0 to remove and 0 not upgraded.
Need to get 6936 kB of archives.
After this operation, 17.3 MB of additional disk space will be used.
...
Get:26 http://deb.debian.org/debian buster/main amd64 rsync amd64 3.1.3-6 [397 kB]
...
Selecting previously unselected package rsync.
Preparing to unpack .../25-rsync_3.1.3-6_amd64.deb ...
Unpacking rsync (3.1.3-6) ...
...
Setting up rsync (3.1.3-6) ...
...
done.
Removing intermediate container a610a0333e97
 ---> 3984df8754b2
```

- CentOS
```console
$ docker build -t "carrodher/percona" .
Sending build context to Docker daemon  30.21kB
Step 1/15 : FROM gcr.io/sys-2b0109it/demo/bitnami/custom-base-image:2019-06
...
Step 5/15 : RUN install_packages ca-certificates curl cyrus-sasl-lib dirmngr glibc gnupg gzip keyutils-libs krb5-libs libaio libcom_err libcurl libev libgcc libgcrypt libgpg-error libidn libselinux libssh2 libstdc++ nspr nss nss-softokn-freebl nss-util openldap openssl-libs pcre procps-ng rsync sudo tar which zlib
 ---> Running in bd5c4e6249dc
...
Resolving Dependencies
--> Running transaction check
...
---> Package rsync.x86_64 0:3.1.2-10.el7 will be installed
...

Dependencies Resolved

================================================================================
 Package                Arch       Version                    Repository   Size
================================================================================
Installing:
 rsync                  x86_64     3.1.2-10.el7               base        404 k
...

Transaction Summary
================================================================================
Install   5 Packages
Upgrade  18 Packages (+4 Dependent packages)

Total download size: 23 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
--------------------------------------------------------------------------------
Total                                               55 MB/s |  23 MB  00:00
Running transaction check
Running transaction test
Transaction test succeeded
...
  Installing : rsync-3.1.2-10.el7.x86_64                                  22/49
...
Installed:
  rsync.x86_64 0:3.1.2-10.el7...

Complete!
Removing intermediate container bd5c4e6249dc
 ---> 1c2e58970c7b
```

- Ubuntu
```console
$ docker build -t "carrodher/percona" .
Sending build context to Docker daemon  29.18kB
Step 1/14 : FROM docker.io/library/ubuntu:18.04
...
Step 5/14 : RUN install_packages ca-certificates curl gzip libaio1 libasn1-8-heimdal libc6 libcom-err2 libcurl4 libev4 libffi6 libgcc1 libgcrypt20 libgmp10 libgnutls30 libgpg-error0 libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhogweed4 libhx509-5-heimdal libidn2-0 libk5crypto3 libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2 libnettle6 libnghttp2-14 libp11-kit0 libpsl5 libroken18-heimdal librtmp1 libsasl2-2 libsqlite3-0 libssl1.1 libstdc++6 libtasn1-6 libunistring2 libwind0-heimdal procps rsync sudo tar zlib1g
 ---> Running in c6986945f38a
Reading package lists...
...
The following NEW packages will be installed:
  ca-certificates curl libaio1 libasn1-8-heimdal libcurl4 libev4
  libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal
  libheimntlm0-heimdal libhx509-5-heimdal libk5crypto3 libkeyutils1
  libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common
  libnghttp2-14 libpopt0 libpsl5 libroken18-heimdal librtmp1 libsasl2-2
  libsasl2-modules-db libsqlite3-0 libssl1.1 libwind0-heimdal openssl rsync
  sudo
...
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 rsync amd64 3.1.2-2.1ubuntu1.1 [334 kB]
...
Selecting previously unselected package rsync.
Preparing to unpack .../12-rsync_3.1.2-2.1ubuntu1.1_amd64.deb ...
Unpacking rsync (3.1.2-2.1ubuntu1.1) ...
...
Setting up rsync (3.1.2-2.1ubuntu1.1) ...
...
Running hooks in /etc/ca-certificates/update.d...
done.
Removing intermediate container c6986945f38a
 ---> 9f310ad18d67
 ```

- PhotonOS
```console
$ docker build -t "carrodher/percona" .
Sending build context to Docker daemon  30.21kB
Step 1/16 : FROM docker.io/library/photon:3.0
...
Step 5/16 : RUN install_packages ca-certificates curl curl-libs e2fsprogs-libs findutils gawk glibc gnupg gzip krb5 libaio libaio-devel libev libgcc libgcrypt libgpg-error libssh2 libstdc++ net-tools openssl procps-ng rsync sed shadow sudo tar util-linux which zlib zstd-libs
 ---> Running in aade6f2e423a
Installing:
...
rsync                    x86_64       3.1.3-3.ph3      photon-updates 496.61k 508531
...

Downloading:
...
Installing/Updating: rsync-3.1.3-3.ph3.x86_64
...

Complete!
Removing intermediate container aade6f2e423a
 ---> d50acc6ba0be
```

I am waiting for an internal review to finally merge the PR, thanks for your patient.

**Pull request merged**
